config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :delete],
  controllers: { sessions: 'users/sessions' }

  resources :students
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  validates :subject_name, presence: true
  validates :marks, presence: true 
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # Add a validation for username
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
  end
  

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  
  def show
  end


  def new
    @student = Student.new
    
  end
  
  def create
    
    existing_student = Student.find_by(name: student_params[:name], subject_name: student_params[:subject_name])
    
    if existing_student
      
      existing_student.update(marks: existing_student.marks + student_params[:marks].to_i)
      redirect_to root_path, notice: 'Student marks were successfully updated.'
    else
    
      @student = Student.new(student_params)
      
      if @student.save
        redirect_to root_path, notice: 'Student was successfully created.'
      else
        render partial: 'form', locals: { student: @student }, status: :unprocessable_entity
      end
    end
  end

  
  def edit
  end


  def update
    if @student.update(student_params)
      redirect_to root_path, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  
  def destroy
    @student.destroy
    redirect_to root_path, notice: 'Student was successfully deleted.'
  end
  
  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :subject_name, :marks)
    end
  end
  

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  def create
    resource = User.find_by(username: params[:user][:username])
    if resource && resource.valid_password?(params[:user][:password])
      sign_in(resource_name, resource)
      redirect_to root_path
    else
      flash[:alert] = 'Invalid username or password.'
      redirect_to new_user_session_path
    end
  end
  

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if notice %>
    <div id="notice" style="background-color: #dff0d8; color: #3c763d; padding: 15px; border-left: 5px solid #4caf50; border-radius: 4px; margin-bottom: 20px; font-size: 1rem;">
      <span style="font-weight: bold; margin-right: 10px;">Notice:</span> <%= notice %>
    </div>
  <% end %>

  <% if alert %>
    <div id="alert" style="background-color: #f2dede; color: #a94442; padding: 15px; border-left: 5px solid #f44336; border-radius: 4px; margin-bottom: 20px; font-size: 1rem;">
      <span style="font-weight: bold; margin-right: 10px;">Alert:</span> <%= alert %>
    </div>
  <% end %>
   <%= turbo_frame_tag "remote_modal" %>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: obj, remote: true, url: obj.new_record? ? students_path : student_path(obj), class: "styled-form") do |form| %>
  <div class="form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-input", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :subject_name, "Subject", class: "form-label" %>
    <%= form.text_field :subject_name, class: "form-input", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :marks, "Mark", class: "form-label" %>
    <%= form.number_field :marks, class: "form-input", required: true %>
  </div>

  <div class="form-actions">
    <%= form.submit "Add", class: "btn-submit" %>
  </div>
<% end %>

<%= link_to 'Back', students_path, class: "back-link" %>

app/views/students/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="<%= classes if defined? classes %>">
    <div id="newModal" class="modal hidden" data-controller="modal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <%= render render_partial, obj: obj, button: button %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
    <%= render partial: "students/form_modal", locals: { obj: @student, render_partial: "students/form", modal_heading: "Add New Student", button: "Save"  } %>
<% end %>

app/views/students/index.html.erb
<div class="header">
  <div class="left-nav">
    <span class="logo-text">tailwebs</span>
  </div>

  <div class="logo">
    
      <%= link_to 'Home', root_path, class: "nav-button" %>
    
    <% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>

    <% end %>
  </div>
</div>
<div class="table-container">
  <table class="styled-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Subject</th>
        <th>Mark</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.subject_name %></td>
          <td><%= student.marks %></td>
            <td class="action-td">
  <div class="dropdown">
    <button type="button" class="dropdown-toggle three-dot">
      <span class="ph--dots-three-bold icons">•••</span>
    </button>
    <ul class="dropdown-menu">
      <li class="dropdown-item">
        <%= link_to edit_student_path(student), class: 'btn btn-edit', "data-controller": "customer" do %>
          <span class="material-symbols-light--edit-outline drop-icon">✏️</span> Edit
        <% end %>
      </li>
      <li class="dropdown-item">
       <%= button_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-delete' %>
      </li>
    </ul>
  </div>
</td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Add', new_student_path, class: "add-button", "data-controller": "customer"  %>
</div>

app/views/students/new.html.erb
<h1><%= action_name.capitalize %> Student</h1>

<%= form_with model: @student, local: true do |form| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :subject_name %>
    <%= form.text_field :subject_name %>
  </div>

  <div>
    <%= form.label :marks %>
    <%= form.number_field :marks %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', students_path %>

app/views/students/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
    <%= render partial: "students/form_modal", locals: { obj: @student, render_partial: "students/form", modal_heading: "Add New Student", button: "Save"  } %>
<% end %>